In [18]:
import numpy as np
import pandas as pd

In [19]:
df=pd.read_csv('movie_dataset.csv',low_memory=False) #read data set
 #make index column as primary column
df.head(2)


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski  

[2 rows x 24 columns]

In [20]:
#Datatype
type(df)

pandas.core.frame.DataFrame

In [21]:
#Column Names
list(df.columns)

['index',
 'budget',
 'genres',
 'homepage',
 'id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count',
 'cast',
 'crew',
 'director']

In [22]:
df.dtypes

index                     int64
budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
director                 object
dtype: object

In [23]:
#Perform Aggregate Function

df.describe(include='all')

index        budget genres                          homepage  \
count   4803.000000  4.803000e+03   4775                              1712   
unique          NaN           NaN   1168                              1691   
top             NaN           NaN  Drama  http://www.thehungergames.movie/   
freq            NaN           NaN    370                                 4   
mean    2401.000000  2.904504e+07    NaN                               NaN   
std     1386.651002  4.072239e+07    NaN                               NaN   
min        0.000000  0.000000e+00    NaN                               NaN   
25%     1200.500000  7.900000e+05    NaN                               NaN   
50%     2401.000000  1.500000e+07    NaN                               NaN   
75%     3601.500000  4.000000e+07    NaN                               NaN   
max     4802.000000  3.800000e+08    NaN                               NaN   

                   id          keywords original_language original_title  \
count     4803.000000              4391              4803           4803   
unique            NaN              4219                37           4801   
top               NaN  independent film                en         Batman   
freq              NaN                55              4505              2   
mean     57165.484281               NaN               NaN            NaN   
std      88694.614033               NaN               NaN            NaN   
min          5.000000               NaN               NaN            NaN   
25%       9014.500000               NaN               NaN            NaN   
50%      14629.000000               NaN               NaN            NaN   
75%      58610.500000               NaN               NaN            NaN   
max     459488.000000               NaN               NaN            NaN   

                                                 overview   popularity  ...  \
count                                                4800  4803.000000  ...   
unique                                               4800          NaN  ...   
top     Young Scottish doctor, Nicholas Garrigan decid...          NaN  ...   
freq                                                    1          NaN  ...   
mean                                                  NaN    21.492301  ...   
std                                                   NaN    31.816650  ...   
min                                                   NaN     0.000000  ...   
25%                                                   NaN     4.668070  ...   
50%                                                   NaN    12.921594  ...   
75%                                                   NaN    28.313505  ...   
max                                                   NaN   875.581305  ...   

            runtime                          spoken_languages    status  \
count   4801.000000                                      4803      4803   
unique          NaN                                       544         3   
top             NaN  [{"iso_639_1": "en", "name": "English"}]  Released   
freq            NaN                                      3171      4795   
mean     106.875859                                       NaN       NaN   
std       22.611935                                       NaN       NaN   
min        0.000000                                       NaN       NaN   
25%       94.000000                                       NaN       NaN   
50%      103.000000                                       NaN       NaN   
75%      118.000000                                       NaN       NaN   
max      338.000000                                       NaN       NaN   

                       tagline     title vote_average    vote_count  \
count                     3959      4803  4803.000000   4803.000000   
unique                    3944      4800          NaN           NaN   
top     Based on a true story.  The Host          NaN           NaN   
freq                         3

In [24]:
#check null data

df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [25]:
#Extract the required feature into feature variable
features=['genres','keywords','director','cast']

#remove null values of homepage and tagline

feat=['homepage','tagline','overview','release_date','runtime']

for feats in feat:
    df[feats]=df[feat].fillna('')
    


In [26]:
for feature in features:
    df[feature]=df[features].fillna('')


In [27]:
df.isnull().sum()

index                   0
budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
director                0
dtype: int64

In [28]:
#Define function to combine features into single comlumn
def combine_feature(row):
    return str(row['genres'])+""+str(row['keywords'])+""+str(row['director'])+""+str(row['cast'])

df['combined features']=df.apply(combine_feature,axis=1)

In [29]:
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                   keywords original_language  \
0  Action Adventure Fantasy Science Fiction                en   
1                  Adventure Fantasy Action                en   
2                    Action Adventure Crime                en   
3               Action Crime Drama Thriller                en   
4          Action Adventure Science Fiction                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                       overview  popularity  ...  \
0                   http://www.avatarmovie.com/  150.437577  ...   
1  http://disney.go.com/disneypictures/pirates/  139.082615  ...   
2   http://www.sonypictures.com/movies/spectre/  107.376788  ...   
3            http://www.thedarkknightrises.com/  112.312950  ...   
4          http://movies.disney.com/john-carter   43.926995  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                        tagline  \
0                   http://www.avatarmovie.com/   
1  http://disney.go.com/disneypictures/pirates/   
2   http://www.sonypictures.com/movies/spectre/   
3            http://www.thedarkknightrises.com/   
4          http://movies.disney.com/john-carter   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                       cast  \
0  Action Adventure Fantasy Science Fiction   
1                  Adventure Fantasy Action   
2                    Action Adventure Crime   
3               Action Crime Drama Thriller   
4          Action Adventure Science Fiction   

                                                crew  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...   
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...   
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...   
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...   

                                   director  \
0  Action Adventure Fantasy Science Fiction   
1                  Adventure Fantasy Action   
2                    Action Adventure Crime   
3               Action Crime Drama Thriller   
4          Action Adventure Science Fiction   

                                   combined features  
0  Action Adventure Fantasy Science FictionAction...  
1  Adventure Fantasy ActionAdv

In [30]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director',
       'combined features'],
      dtype='object')

#Data vectorization

In [31]:
#Tokenization and vectorization

from sklearn.feature_extraction.text import CountVectorizer

In [32]:
cv=CountVectorizer()

In [62]:
# Prints dict of key-value pair
print(cv.vocabulary_)

{'action': 0, 'adventure': 16, 'fantasy': 116, 'science': 222, 'fictionaction': 129, 'fiction': 128, 'actionadventure': 2, 'crimeaction': 59, 'crime': 58, 'drama': 81, 'thrilleraction': 224, 'thriller': 223, 'adventurefantasy': 25, 'animation': 32, 'familyanimation': 104, 'family': 101, 'familyadventure': 103, 'fantasyaction': 117, 'fictionadventure': 130, 'crimeadventure': 60, 'westernaction': 253, 'western': 252, 'fantasyadventure': 118, 'adventurescience': 29, 'comedy': 41, 'adventureaction': 17, 'romance': 207, 'thrillerdrama': 229, 'fictionthriller': 141, 'adventurefamily': 24, 'thrilleradventure': 225, 'familyfantasy': 110, 'comedyanimation': 44, 'actionactionactionaction': 1, 'horror': 162, 'romancedrama': 213, 'romanceadventure': 209, 'actionanimation': 3, 'dramaanimation': 84, 'fictionscience': 140, 'adventureanimation': 19, 'fictionanimation': 131, 'familydrama': 108, 'fantasyfamily': 122, 'dramaadventure': 83, 'romancefantasy': 215, 'thrillerscience': 235, 'romanceaction': 2

In [34]:
# word counting
x=cv.fit_transform(df['combined features']) #x is a sparse matrix
print(x.toarray())
print(type(x))

[[1 0 0 ... 0 0 0]
 [1 0 3 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'scipy.sparse.csr.csr_matrix'>


In [35]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [36]:
A_sparse=sparse.csr_matrix(x) #convert sparse matrix to cosine Similarity Matrix
similarity_score=cosine_similarity(A_sparse,dense_output=True) #if False then sparse output is returned

In [37]:
print(similarity_score)

[[1.         0.52615222 0.42593275 ... 0.         0.         0.        ]
 [0.52615222 1.         0.18518519 ... 0.         0.         0.        ]
 [0.42593275 0.18518519 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [38]:
df['index']

0          0
1          1
2          2
3          3
4          4
        ... 
4798    4798
4799    4799
4800    4800
4801    4801
4802    4802
Name: index, Length: 4803, dtype: int64

In [56]:
def gt_title(tit):
    return df[df.index==tit]['title'].values[0]

def gt_index(ind):
    return df[df.title==ind]['index'].values[0]

In [57]:
#take value from user and search for similiar movies
input_user=input('\n Enter a movie name \n')
movie_index=gt_index(input_user)
similiar_movies=list(enumerate(similarity_score[movie_index]))


 Enter a movie name 
Harry Potter and the Half-Blood Prince


In [58]:
sorted_similiar_movies=sorted(similiar_movies,key=lambda x:x[1],reverse=True)[1:] #Descending values

In [61]:
i=0
print('Top 5 similiar movies are \n')
for element in sorted_similiar_movies:
    print(gt_title(element[0]))
    
    i=i+1
    if i>5:
        break


Top 5 similiar movies are 

Harry Potter and the Goblet of Fire
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Philosopher's Stone
Harry Potter and the Chamber of Secrets
Percy Jackson & the Olympians: The Lightning Thief
Night at the Museum: Secret of the Tomb


In [63]:
df[['original_title','title']]

original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                         title  
0                                       Avatar  
1     Pirates of the Caribbean: At World's End  
2                                      Spectre  
3                        The Dark Knight Rises  
4                                  John Carter  
...                                        ...  
4798                               El Mariachi  
4799                                 Newlyweds  
4800                 Signed, Sealed, Delivered  
4801                          Shanghai Calling  
4802                         My Date with Drew  

[4803 rows x 2 columns]